name: base
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - requests
  - plotly
  - scikit-learn=0.21
  - pip
    - shap
